src/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^jobs/create/$', views.NewJobPage.as_view(), name='new_job'),
    url(r'^jobs/$', views.JobsPage.as_view(), name='jobs'),
    url(r'^jobs/view/(?P<print_id>[^/]+)/$', views.JobPage.as_view(), name='view_job'),
    url(r'^jobs/manage/(?P<print_id>[^/]+)/$', views.ManageJobPage.as_view(), name='manage_job'),
    url(r'^jobs/edit/(?P<print_id>[^/]+)/$', views.EditJobPage.as_view(), name='edit_job'),
]

src/postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    (r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import url

if getattr(settings, 'POSTMAN_I18N_URLS', False):
    from django.utils.translation import pgettext_lazy
else:
    def pgettext_lazy(c, m):
        return m
from django.views.generic.base import RedirectView

from .views import (InboxView, SentView, ArchivesView, TrashView,
                    WriteView, ReplyView, MessageView, ConversationView,
                    ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView)

urlpatterns = [
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^inbox/(?:(?P<option>m)/)?$'), InboxView.as_view(), name='inbox'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^sent/(?:(?P<option>m)/)?$'), SentView.as_view(), name='sent'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^archives/(?:(?P<option>m)/)?$'), ArchivesView.as_view(), name='archives'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    url(pgettext_lazy('postman_url', r'^trash/(?:(?P<option>m)/)?$'), TrashView.as_view(), name='trash'),
    url(pgettext_lazy('postman_url', r'^write/(?:(?P<recipients>[^/#]+)/)?$'),
        WriteView.as_view(autocomplete_channels='postman_users', ), name='write'),
    url(pgettext_lazy('postman_url', r'^reply/(?P<message_id>[\d]+)/$'), ReplyView.as_view(), name='reply'),
    url(pgettext_lazy('postman_url', r'^view/(?P<message_id>[\d]+)/$'), MessageView.as_view(), name='view'),
    # Translators: 't' stands for 'thread'
    url(pgettext_lazy('postman_url', r'^view/t/(?P<thread_id>[\d]+)/$'), ConversationView.as_view(),
        name='view_conversation'),
    url(pgettext_lazy('postman_url', r'^archive/$'), ArchiveView.as_view(), name='archive'),
    url(pgettext_lazy('postman_url', r'^delete/$'), DeleteView.as_view(), name='delete'),
    url(pgettext_lazy('postman_url', r'^undelete/$'), UndeleteView.as_view(), name='undelete'),
    url(pgettext_lazy('postman_url', r'^mark-read/$'), MarkReadView.as_view(), name='mark-read'),
    url(pgettext_lazy('postman_url', r'^mark-unread/$'), MarkUnreadView.as_view(), name='mark-unread'),
    url(r'^$', RedirectView.as_view(url='inbox/', permanent=True)),
]

src/print_queue/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

import accounts.urls
import app.urls
import profiles.urls
from . import views

urlpatterns = [
    url(r'^faq/', views.FAQPage.as_view(), name='faq'),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    url(r'^', include(app.urls, namespace='app')),
    url(r'^', include(accounts.urls, namespace='accounts')),
]
if settings.DEBUG is True:
    # User-uploaded files like profile pics need to be served in development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Include django debug toolbar if DEBUG is on
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

src/app/templates/app/edit_job.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Print Job{% endblock %}

{% block navbar-left %}
    {% include "_navbar.html" with active_link="jobs" %}
{% endblock %}

{% block container %}

    <div id="sec1" class="text-page">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>{% include "_brandname.html" %}</h1>
                    <p class="lead"><strong>Job: {{ job.print_name }}</strong></p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            {% crispy job_form %}
        </div>
    </div>

{% endblock %}

src/app/templates/app/job.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Print Job{% endblock %}

{% block navbar-left %}
    {% include "_navbar.html" %}
{% endblock %}

{% block container %}

    <div id="sec1" class="text-page">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>{% include "_brandname.html" %}</h1>
                    <p class="lead"><strong>Print Job</strong></p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">

        </div>
    </div>

{% endblock %}

src/app/templates/app/jobs.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Jobs{% endblock %}

{% block navbar-left %}
    {% include "_navbar.html" with active_link="jobs" %}
{% endblock %}

{% block extrahead %}
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/bs/jqc-1.12.4/dt-1.10.13/fh-3.1.2/r-2.1.1/sc-1.4.2/datatables.min.css"/>
{% endblock extrahead %}

{% block container %}

    <div id="cf4a" class="text-page">
        {#        <img class="top-img" src="{% static 'site/img/slides/slide1.png' %}">#}
        {#        <img class="top-mid-img" src="{% static 'site/img/slides/slide2.png' %}">#}
        {#        <img class="bottom-mid-img" src="{% static 'site/img/slides/slide3.png' %}">#}
        {#        <img class="bottom-img" src="{% static 'site/img/slides/slide4.png' %}">#}
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>{% include "_brandname.html" %}</h1>
                    <p class="lead"><strong>Print Jobs</strong></p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <br>
        <div class="center-block"><a href="{% url 'app:new_job' %}">
            <button class="btn btn-success"><span class="glyphicon glyphicon-plus"></span> New Job</button>
        </a></div>
        <br>
        {% if not jobs %}
            <div class="row">
                <div class="text-center text-danger text-capitalize">
                    <h3>No Print Jobs submitted</h3>
                </div>
            </div>
        {% else %}
            <div class="table table-responsive">
                <table class="table" id="job_table">
                    <thead>
                    <tr>
                        <th>Submitted on</th>
                        <th>Print Name</th>
                        {% if user.is_staff %}
                            <th>Requested By</th>
                            <th>Waiting for</th>
                        {% endif %}
                        <th>Job Status</th>
                        <th>Link</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for job in jobs %}
                        <tr>
                            <td>{{ job.datetime_submitted }}</td>
                            <td>{{ job.print_name }}</td>
                            {% if user.is_staff %}
                                <td>{{ job.requester.user.name }}</td>
                                {% if job.datetime_actioned == None %}
                                    <td>{{ job.datetime_submitted|timesince }}</td>
                                {% else %}
                                    <td>{{ job.datetime_actioned|timesince }}</td>
                                {% endif %}
                            {% endif %}
                            <td>{{ job.job_status }}</td>
                            {% if user.is_staff %}
                                <td><a href="{% url 'app:manage_job' print_id=job.print_id %}">Manage</a></td>
                            {% else %}
                            <td><a href="{% url 'app:view_job' print_id=job.print_id %}">View</a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
    </div>

{% endblock %}
{% block scripts %}
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/bs/jqc-1.12.4/dt-1.10.13/fh-3.1.2/r-2.1.1/sc-1.4.2/datatables.min.css"/>
    <script type="text/javascript"
            src="https://cdn.datatables.net/v/bs/jqc-1.12.4/dt-1.10.13/fh-3.1.2/r-2.1.1/sc-1.4.2/datatables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#job_table').DataTable({
                select: true,
                autowidth: true
            });
        });
    </script>
{% endblock scripts %}

src/app/templates/app/manage_job.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Print Job{% endblock %}

{% block navbar-left %}
    {% include "_navbar.html" with active_link="jobs" %}
{% endblock %}

{% block container %}

    <div id="sec1" class="text-page">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>{% include "_brandname.html" %}</h1>
                    <p class="lead"><strong>Job: {{ job.print_name }}</strong></p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <br>
            <div class="center-block"><a
                    href="{% url 'postman:write' recipients=job.requester.user.name|urlencode %}?subject=Re:{{ job.print_name|urlencode }}">
                <button class="btn btn-info"><span class="glyphicon glyphicon-edit"></span> Compose</button>
            </a>
            </div>
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <ul class="list-group">
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Job Name:</strong></span> {{ job.print_name }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Requested by:</strong></span> {{ job.requester.user.name }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Submitted:</strong></span> {{ job.datetime_submitted }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Actioned:</strong></span> {{ job.datetime_actioned }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Job Status:</strong></span> {{ job.job_status }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Notes:</strong></span> {{ job.notes }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>File:</strong></span> <a href="{{ job.file.url }}">Download</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2"></div>
        </div>
        <div class="row">
            {% crispy manage_form %}
        </div>
    </div>

{% endblock %}

src/app/templates/app/new_job.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}New Job{% endblock %}

{% block navbar-left %}
    {% include "_navbar.html" with active_link="jobs" %}
{% endblock %}

{% block container %}

    <div id="sec1" class="text-page">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>{% include "_brandname.html" %}</h1>
                    <p class="lead"><strong>New Print Job</strong></p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            {% crispy job_form %}
        </div>
    </div>

{% endblock %}

src/app/templates/app/view_job.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}

{% block title %}{{ block.super }}Print Job{% endblock %}

{% block navbar-left %}
    {% include "_navbar.html" with active_link="jobs" %}
{% endblock %}

{% block container %}

    <div id="sec1" class="text-page">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>{% include "_brandname.html" %}</h1>
                    <p class="lead"><strong>Job: {{ job.print_name }}</strong></p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <br>
            <div class="center-block"><a href="{% url 'app:edit_job' print_id=job.print_id %}">
                <button class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit Job</button>
            </a>
            </div>
            <br>
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <ul class="list-group">
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Job Name:</strong></span> {{ job.print_name }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Submitted:</strong></span> {{ job.datetime_submitted }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Actioned:</strong></span> {{ job.datetime_actioned }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Job Status:</strong></span> {{ job.job_status }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>Notes:</strong></span> {{ job.notes }}</li>
                    <li class="list-group-item text-right"><span
                            class="pull-left"><strong>File:</strong></span> <a href="{{ job.file.url }}">Download</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>

{% endblock %}